/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoreWorksRouteImport } from './routes/more-works'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudySlugRouteImport } from './routes/case-study.$slug'

const MoreWorksRoute = MoreWorksRouteImport.update({
  id: '/more-works',
  path: '/more-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudySlugRoute = CaseStudySlugRouteImport.update({
  id: '/case-study/$slug',
  path: '/case-study/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-works': typeof MoreWorksRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-works': typeof MoreWorksRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/more-works': typeof MoreWorksRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/more-works' | '/case-study/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/more-works' | '/case-study/$slug'
  id: '__root__' | '/' | '/about' | '/more-works' | '/case-study/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MoreWorksRoute: typeof MoreWorksRoute
  CaseStudySlugRoute: typeof CaseStudySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/more-works': {
      id: '/more-works'
      path: '/more-works'
      fullPath: '/more-works'
      preLoaderRoute: typeof MoreWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/$slug': {
      id: '/case-study/$slug'
      path: '/case-study/$slug'
      fullPath: '/case-study/$slug'
      preLoaderRoute: typeof CaseStudySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MoreWorksRoute: MoreWorksRoute,
  CaseStudySlugRoute: CaseStudySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
